name: ci.yml
on:
  push:
    branches:
      - "feature/**"

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'OpenJDK'
          cache: 'maven'
      - name: Build and Test with maven
        run: mvn -B test --file pom.xml
