name: mainMergeJarUpload.yml
on:
  push:
    branches:
      - 'main'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'OpenJDK'
          cache: 'maven'

      - name: Build Project
        run: mvn -B clean package

      - name: Upload JAR
        run: |
          mkdir staging
          cp target/sumpdata-*.jar staging

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sumpdata-jar
          path: staging
